# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37215e09fc13f747d7acba200248c055eccf00b4bc68fdde4dd9d3b77f71af936888b1b788438dfeb1dc299e53200ee808cd75bf385d0ecbc801b8a656e7ef7d

test:
  secret_key_base: a7f0279c507654c8ab517d9de1d6ba555d4dc719b53e6a28a67121efe9fef42ec7ee8db9cddc5006fc2b0724162ebfc3c085daadea492765759677859d412d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
